
CREATE TABLE ROLES (
    RoleID VARCHAR(10) PRIMARY KEY,
    RoleName VARCHAR(50)
);


CREATE TABLE EMPLOYEE (
    EmpID VARCHAR(10) PRIMARY KEY,
    FullName VARCHAR(100),
    JobTitle VARCHAR(50),
    Department VARCHAR(50),
    Email VARCHAR(100),
    RoleID VARCHAR(10) REFERENCES ROLES(RoleID)
);


CREATE TABLE SUPPLIERS (
    SupplierID SERIAL PRIMARY KEY,
    Name VARCHAR(100),
    ContactEmail VARCHAR(100),
    Category VARCHAR(50)
);


CREATE TABLE PARTS (
    PartID SERIAL PRIMARY KEY,
    PartName VARCHAR(100),
    SKU VARCHAR(50) UNIQUE,
    StockLevel INTEGER
);


CREATE TABLE ORDERS (
    OrderID SERIAL PRIMARY KEY,
    PartID INTEGER REFERENCES PARTS(PartID),
    SupplierID INTEGER REFERENCES SUPPLIERS(SupplierID),
    Quantity INTEGER,
    OrderDate DATE DEFAULT CURRENT_DATE
);


CREATE TABLE SHIPMENTS (
    ShipmentID SERIAL PRIMARY KEY,
    OrderID INTEGER REFERENCES ORDERS(OrderID),
    Status VARCHAR(50), 
    DeliveryDate DATE
);